import { defineConfig } from 'vitepress';

const repo = 'https://github.com/TinkerDoge/FoxFleet';

export default defineConfig({
  title: 'Foxfleet',
  description: 'Self-hosted hub, web app and Android app for talking to all your AI agents from one calm place.',
  base: '/FoxFleet/',
  lang: 'en',
  cleanUrls: true,
  lastUpdated: false,
  srcExclude: ['README.md', 'node_modules/**'],
  head: [
    ['link', { rel: 'icon', type: 'image/png', href: '/FoxFleet/favicon.png' }],
    ['meta', { name: 'theme-color', content: '#BE4A21' }],
    ['meta', { property: 'og:title', content: 'Foxfleet docs' }],
    ['meta', { property: 'og:image', content: 'https://tinkerdoge.github.io/FoxFleet/img/web-chat.png' }],
  ],
  themeConfig: {
    logo: { light: '/wordmark-light.png', dark: '/wordmark-dark.png', alt: 'Foxfleet' },
    siteTitle: false,
    search: { provider: 'local' },
    editLink: { pattern: `${repo}/edit/main/site/:path`, text: 'Edit this page on GitHub' },
    socialLinks: [{ icon: 'github', link: repo }],
    nav: [
      { text: 'Get started', link: '/guide/quick-start' },
      { text: 'Concepts', link: '/concepts/' },
      { text: 'Host it', link: '/hosting/' },
      { text: 'Agents', link: '/agents/' },
      { text: 'Apps', link: '/apps/chat' },
      { text: 'Reference', link: '/reference/api' },
      { text: 'More', items: [
        { text: 'Security', link: '/security/' },
        { text: 'Roadmap', link: '/project/roadmap' },
        { text: 'Changelog', link: '/project/changelog' },
        { text: 'Contributing', link: '/project/contributing' },
        { text: 'FAQ and troubleshooting', link: '/faq' },
        { text: 'Support and credits', link: '/support' },
      ] },
    ],
    sidebar: {
      '/guide/': [{ text: 'Getting started', items: [
        { text: '5-minute quick start', link: '/guide/quick-start' },
        { text: 'First run: the owner account', link: '/guide/first-run' },
        { text: 'Install the Android app', link: '/guide/android' },
      ] }],
      '/concepts/': [{ text: 'Concepts', items: [
        { text: 'Overview', link: '/concepts/' },
        { text: 'Accounts and roles', link: '/concepts/accounts' },
        { text: 'Agents, kinds and capabilities', link: '/concepts/agents' },
        { text: 'The connector', link: '/concepts/connector' },
        { text: 'Sessions and devices', link: '/concepts/sessions-devices' },
      ] }],
      '/hosting/': [{ text: 'Hosting', items: [
        { text: 'Overview', link: '/hosting/' },
        { text: 'Linux with systemd', link: '/hosting/systemd' },
        { text: 'Docker Compose', link: '/hosting/docker' },
        { text: 'Cloudflare Tunnel', link: '/hosting/cloudflare-tunnel' },
        { text: 'Caddy and nginx', link: '/hosting/reverse-proxy' },
        { text: 'Environment variables', link: '/hosting/environment' },
        { text: 'Data directory', link: '/hosting/data' },
        { text: 'Backups and restore', link: '/hosting/backups' },
        { text: 'Upgrading and rollback', link: '/hosting/upgrading' },
        { text: 'Resource sizing', link: '/hosting/sizing' },
        { text: 'Migrating from AgentsHub', link: '/hosting/migrating' },
      ] }],
      '/agents/': [{ text: 'Onboarding agents', items: [
        { text: 'Overview', link: '/agents/' },
        { text: 'Connect a real-machine agent', link: '/agents/real-machine' },
        { text: 'Hermes', link: '/agents/hermes' },
        { text: 'OpenAI-compatible', link: '/agents/openai' },
        { text: 'OpenRouter', link: '/agents/openrouter' },
        { text: 'Z.ai (GLM)', link: '/agents/zai' },
        { text: 'OpenCode', link: '/agents/opencode' },
        { text: 'Grok (xAI)', link: '/agents/grok' },
        { text: 'MCP inbox', link: '/agents/mcp-inbox' },
        { text: 'Screen takeover setup', link: '/agents/screen-setup' },
        { text: 'Write your own plugin', link: '/agents/write-a-plugin' },
      ] }],
      '/apps/': [{ text: 'Using the apps', items: [
        { text: 'Chat', link: '/apps/chat' },
        { text: 'Attachments and voice', link: '/apps/attachments' },
        { text: 'Commands', link: '/apps/commands' },
        { text: 'Media viewer', link: '/apps/media-viewer' },
        { text: 'Screen takeover', link: '/apps/screen' },
        { text: 'Admin', link: '/apps/admin' },
        { text: 'Settings and devices', link: '/apps/settings' },
        { text: 'Avatars', link: '/apps/avatars' },
      ] }],
      '/security/': [{ text: 'Security', items: [
        { text: 'Overview and threat model', link: '/security/' },
        { text: 'Authentication', link: '/security/auth' },
        { text: 'Secrets and privacy', link: '/security/secrets' },
        { text: 'Media proxy (SSRF)', link: '/security/media-proxy' },
        { text: 'Takeover safeguards', link: '/security/takeover' },
        { text: 'Reporting a problem', link: '/security/reporting' },
      ] }],
      '/reference/': [{ text: 'Reference', items: [
        { text: 'REST API', link: '/reference/api' },
        { text: 'Connector protocol', link: '/reference/connector-protocol' },
        { text: 'config.json (v3)', link: '/reference/config-json' },
        { text: 'Error codes', link: '/reference/errors' },
        { text: 'Environment variables', link: '/hosting/environment' },
      ] }],
      '/project/': [{ text: 'Project', items: [
        { text: 'Roadmap', link: '/project/roadmap' },
        { text: 'Changelog', link: '/project/changelog' },
        { text: 'Contributing', link: '/project/contributing' },
        { text: 'Development', link: '/project/development' },
        { text: 'Design tokens', link: '/project/design-tokens' },
        { text: 'Accessibility', link: '/project/accessibility' },
        { text: 'Release process', link: '/project/release' },
      ] }],
    },
    footer: { message: 'MIT licensed. Free software with optional tips.', copyright: 'Foxfleet contributors' },
    outline: { level: [2, 3] },
  },
});
