package dev.foxfleet.app.screenshots

import androidx.compose.runtime.Composable
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onRoot
import com.github.takahirom.roborazzi.captureRoboImage
import dev.foxfleet.app.data.AgentStatus
import dev.foxfleet.app.data.AppPrefs
import dev.foxfleet.app.data.ImageAttachment
import dev.foxfleet.app.data.Machine
import dev.foxfleet.app.data.Pairing
import dev.foxfleet.app.data.PairingState
import dev.foxfleet.app.data.ThemeMode
import dev.foxfleet.app.data.UiMessage
import dev.foxfleet.app.ui.FoxfleetTheme
import dev.foxfleet.app.ui.chat.ChatState
import dev.foxfleet.app.ui.screens.ChatScreen
import dev.foxfleet.app.ui.screens.FleetScreen
import dev.foxfleet.app.ui.screens.MachinesContent
import dev.foxfleet.app.ui.screens.ScreenPhase
import dev.foxfleet.app.ui.screens.ScreenScreen
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode
import java.io.File

private val OUT = System.getProperty("foxfleet.shots") ?: "build/outputs/roborazzi"

/** Looks for design/demo/<name> (generated by design/tools/demo_assets.py) from the module or the repo root. */
private fun demo(name: String): File = listOf("../../design/demo/$name", "design/demo/$name", "../design/demo/$name").map(::File).firstOrNull { it.exists() }
    ?: error("Run design/tools/demo_assets.py first: design/demo/$name is missing")

private val fleetAgents = listOf(
    AgentStatus("Atlas", online = true, chatReady = true, managementReady = true, activeSessions = 2, description = "Research and code on the workstation"),
    AgentStatus("Coder", online = true, chatReady = true, managementReady = true, description = "Reviews and refactors the repos"),
    AgentStatus("Research", online = true, chatReady = true, managementReady = true, description = "Reads papers and summarises them"),
    AgentStatus("Nova", online = true, chatReady = true, managementReady = false, kind = "openrouter", description = "Fast general chat"),
    AgentStatus("Echo", online = false, chatReady = false, managementReady = false, kind = "openai", description = "Needs a new API key"),
)

private val QR_ROWS = listOf(
    "11111110111010100110001111111",
    "10000010111000000001001000001",
    "10111010101101011111101011101",
    "10111010110100101001001011101",
    "10111010000001101110001011101",
    "10000010100111100101001000001",
    "11111110101010101010101111111",
    "00000000010010110111000000000",
    "11001110000101101101100101111",
    "01111000111010010010001111111",
    "11010111000111111000001110001",
    "11001100101101010111101011011",
    "01011111001011000110110000010",
    "11110100100001101110111011111",
    "01001011001000011010110111101",
    "10111100001010111110111100011",
    "00010110011101101001110000010",
    "11010100111010001110001111011",
    "00100111111111111000011000101",
    "00011100100101001110101000011",
    "11010010011011001110111111001",
    "00000000101001110001100010001",
    "11111110001000011011101011101",
    "10000010110010111111100010011",
    "10111010100101111001111111010",
    "10111010010010001001110100001",
    "10111010011111110100010001111",
    "10000010101101010111100101011",
    "11111110111011010000110001010"
)

/** Polished, realistic scenes for the README and docs images (generic names, real generated pictures; no placeholders). */
@RunWith(RobolectricTestRunner::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@Config(sdk = [34], qualifiers = "w411dp-h891dp-xxhdpi")
class ReadmeScreenshotTest {
    @get:Rule val compose = createComposeRule()

    private fun shot(name: String, dark: Boolean, content: @Composable () -> Unit) {
        compose.mainClock.autoAdvance = false
        compose.setContent { FoxfleetTheme(AppPrefs(theme = if (dark) ThemeMode.Dark else ThemeMode.Light)) { content() } }
        compose.mainClock.advanceTimeBy(900)
        compose.onRoot().captureRoboImage("$OUT/readme-$name-${if (dark) "dark" else "light"}.png")
    }

    private fun fleet(dark: Boolean) = shot("fleet", dark) {
        FleetScreen(fleetAgents, loading = false, loadedOnce = true, error = null, unread = { it.name == "Nova" }, onRefresh = {}, onOpen = {}, onSettings = {})
    }

    private val reply = """
        |## Weekly summary
        |Atlas handled most of the load; **Friday** was the busiest day.
        |
        || Agent | Tokens |
        ||---|---:|
        || Atlas | 1.19M |
        || Nova | 0.74M |
        || Echo | 0.29M |
        |
        |```python
        |def weekly_tokens(rows):
        |    totals = {}
        |    for agent, tokens in rows:
        |        totals[agent] = totals.get(agent, 0) + tokens
        |    return totals
        |```
        |Echo needs a new API key before I can re-run this.
        """.trimMargin()

    private fun chat(dark: Boolean) {
        val photoFile = File.createTempFile("demo", ".jpg").also { demo("photo.jpg").copyTo(it, overwrite = true) }
        val pic = ImageAttachment(photoFile.absolutePath, "data:image/jpeg;base64,AA", 10)
        val state = ChatState().apply {
            load(listOf(
                UiMessage("user", "Can you summarise last week’s activity? I’m attaching the photo from the offsite for the report.", images = listOf(pic)),
                UiMessage("assistant", reply),
            ), "a1b2c3d4e5")
        }
        shot("chat", dark) { ChatScreen(fleetAgents[0], fleetAgents, state, emptyList(), { false }, { _, _ -> }, {}, {}, {}, {}, {}, {}) }
    }

    private fun streaming(dark: Boolean) {
        val state = ChatState().apply {
            load(listOf(UiMessage("user", "Find the three biggest risks in the release checklist."), ), "a1b2c3d4e5")
            simulateStream("Reading the checklist and cross-checking it against the open issues. So far the biggest risk is that the Docker image build has not", tool = "Searching the docs")
        }
        shot("chat-streaming", dark) { ChatScreen(fleetAgents[0], fleetAgents, state, emptyList(), { false }, { _, _ -> }, {}, {}, {}, {}, {}, {}) }
    }

    private fun machines(dark: Boolean) {
        val url = "https://hub.example.com/c/K7QMX2PD4H"
        val m = Machine("a".repeat(32), "Workstation", true, null, listOf("default", "coder", "research"))
        val pairing = Pairing("K7QMX2PD4H", "K7QMX-2PD4H", System.currentTimeMillis() + 15 * 60_000, url, "foxfleet://pair?hub=https%3A%2F%2Fhub.example.com&code=K7QMX2PD4H",
            QR_ROWS, "curl -fsSL $url | sh", "irm $url.ps1 | iex", "node …")
        shot("machines", dark) { MachinesContent(listOf(m), pairing, PairingState.Paired(m), null, {}, {}, {}, {}, {}) }
    }

    private fun screen() {
        val bmp = android.graphics.BitmapFactory.decodeFile(demo("desktop.png").absolutePath)
        shot("screen", true) {
            ScreenScreen("Atlas", api = null, onBack = {}, onLeaveInControl = {}, preview = true, initialPhase = ScreenPhase.Control,
                initialHandBackAt = System.currentTimeMillis() + 14 * 60_000 + 30_000, previewFrame = bmp)
        }
    }

    @Test fun fleetLight() = fleet(false)
    @Test fun fleetDark() = fleet(true)
    @Test fun chatLight() = chat(false)
    @Test fun chatDark() = chat(true)
    @Test fun streamingLight() = streaming(false)
    @Test fun machinesDark() = machines(true)
    @Test fun machinesLight() = machines(false)
    @Test fun screenDark() = screen()
}
