// GENERATED by design/tools/gen-tokens.mjs from design/tokens.json. Do not edit.
package dev.foxfleet.app.ui

import androidx.compose.ui.graphics.Color

object Tokens {
    /** Accent presets: name to (light, dark) tone. Index is what SettingsStore persists. */
    val accents: List<Triple<String, Color, Color>> = listOf(
        Triple("Ember", Color(0xFFBE4A21), Color(0xFFF08A5D)),
        Triple("Ocean", Color(0xFF2A64C6), Color(0xFF6EA2FF)),
        Triple("Moss", Color(0xFF2F7A4B), Color(0xFF6CC58E)),
        Triple("Iris", Color(0xFF7457D8), Color(0xFFA48DFF)),
        Triple("Graphite", Color(0xFF3A3A3A), Color(0xFFE6E6E6)),
    )
    object Light {
        val bg = Color(0xFFF7F5F2)
        val surface = Color(0xFFFFFFFF)
        val surfaceAlt = Color(0xFFEFECE7)
        val hairline = Color(0x1A000000)
        val text = Color(0xFF1B1B1C)
        val textMuted = Color(0xFF66625D)
        val textFaint = Color(0xFF68635D)
        val online = Color(0xFF2E9E66)
        val onlineText = Color(0xFF1D6841)
        val idle = Color(0xFFC08A1E)
        val idleText = Color(0xFF79520B)
        val offline = Color(0xFFC4BFB8)
        val danger = Color(0xFFC0392B)
        const val userBubbleAlpha = 0.12f
    }
    object Dark {
        val bg = Color(0xFF0E0E0F)
        val surface = Color(0xFF17171A)
        val surfaceAlt = Color(0xFF1F1F23)
        val hairline = Color(0x1FFFFFFF)
        val text = Color(0xFFEDEDED)
        val textMuted = Color(0xFFA1A1A6)
        val textFaint = Color(0xFF939399)
        val online = Color(0xFF4CC38A)
        val onlineText = Color(0xFF6ACF9D)
        val idle = Color(0xFFE0B04A)
        val idleText = Color(0xFFE0B04A)
        val offline = Color(0xFF4A4A50)
        val danger = Color(0xFFFF6B5E)
        const val userBubbleAlpha = 0.16f
    }
    const val radiusCard = 16
    const val radiusControl = 12
    const val radiusSmall = 8
    const val radiusPill = 999
    const val motionFastMs = 120
    const val motionBaseMs = 200
    const val motionSlowMs = 320
    const val motionPressMs = 90
    const val motionMessageInMs = 180
    const val motionStatusMs = 180
    const val motionPanelInMs = 240
    const val motionPanelOutMs = 150
    const val motionTypingPhaseMs = 150
    const val motionTypingLoopMs = 600
    /** Minimum touch target (dp). */
    const val touchTarget = 44
}
