#!/usr/bin/env node
// Generates web/src/styles/tokens.css and android/.../ui/Tokens.kt from design/tokens.json.
// `--check` exits 1 when the generated files are stale (used by CI and the web tests).
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const t = JSON.parse(readFileSync(path.join(root, 'design', 'tokens.json'), 'utf8'));
const kebab = (s) => s.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());
const hex = (v) => { if (!/^#[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$/.test(v)) throw new Error(`Bad colour ${v}`); return v.toUpperCase(); };
const kt = (v) => { const h = hex(v).slice(1); return `Color(0x${h.length === 8 ? h.slice(6) + h.slice(0, 6) : 'FF' + h})`; };

export function css() {
  const palette = (mode) => Object.entries(t.colors[mode]).map(([k, v]) => `  --${kebab(k)}: ${hex(v)};`).join('\n');
  const accent = (mode, a) => `  --accent: ${hex(a[mode])};\n  --on-accent: ${lum(a[mode]) > 0.55 ? '#111111' : '#FFFFFF'};`;
  const accents = (mode, scope) => t.accents.map((a, i) => `${scope}[data-accent="${a.id}"] {\n${accent(mode, a)}\n}`).join('\n');
  const bubble = (mode) => `  --user-bubble: color-mix(in srgb, var(--accent) ${Math.round(t.userBubbleAlpha[mode] * 100)}%, transparent);`;
  const s = t.type.scale;
  return `/* GENERATED by design/tools/gen-tokens.mjs from design/tokens.json. Do not edit. */
:root {
  color-scheme: light dark;
${palette('light')}
${accent('light', t.accents[0])}
${bubble('light')}
${Object.entries(t.radius).map(([k, v]) => `  --radius-${kebab(k)}: ${v}px;`).join('\n')}
${Object.entries(t.space).map(([k, v]) => `  --space-${kebab(k)}: ${v}px;`).join('\n')}
  --font: ${t.type.family};
  --font-mono: ${t.type.mono};
${Object.entries(s).map(([k, v]) => `  --text-${kebab(k)}: ${v.size}px/${v.line}px;\n  --weight-${kebab(k)}: ${v.weight};`).join('\n')}
${Object.entries(t.motion).map(([k, v]) => `  --motion-${k}: ${v}ms;`).join('\n')}
}
${accents('light', ':root')}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${palette('dark').replace(/^/gm, '  ')}
${accent('dark', t.accents[0]).replace(/^/gm, '  ')}
${bubble('dark').replace(/^/gm, '  ')}
  }
${accents('dark', '  :root:not([data-theme="light"])').replace(/^/gm, '  ')}
}
:root[data-theme="dark"] {
${palette('dark')}
${accent('dark', t.accents[0])}
${bubble('dark')}
}
${accents('dark', ':root[data-theme="dark"]')}
@media (prefers-reduced-motion: reduce) { :root { --motion-fast: 0ms; --motion-base: 0ms; --motion-slow: 0ms; } }
`;
}

function lum(v) { const h = hex(v).slice(1); const [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255); return 0.2126 * r + 0.7152 * g + 0.0722 * b; }
const camel = (s) => s;

export function kotlin() {
  const group = (mode) => Object.entries(t.colors[mode]).map(([k, v]) => `        val ${camel(k)} = ${kt(v)}`).join('\n');
  return `// GENERATED by design/tools/gen-tokens.mjs from design/tokens.json. Do not edit.
package dev.foxfleet.app.ui

import androidx.compose.ui.graphics.Color

object Tokens {
    /** Accent presets: name to (light, dark) tone. Index is what SettingsStore persists. */
    val accents: List<Triple<String, Color, Color>> = listOf(
${t.accents.map((a) => `        Triple("${a.name}", ${kt(a.light)}, ${kt(a.dark)}),`).join('\n')}
    )
    object Light {
${group('light')}
        const val userBubbleAlpha = ${t.userBubbleAlpha.light}f
    }
    object Dark {
${group('dark')}
        const val userBubbleAlpha = ${t.userBubbleAlpha.dark}f
    }
${Object.entries(t.radius).map(([k, v]) => `    const val radius${k[0].toUpperCase() + k.slice(1)} = ${v}`).join('\n')}
${Object.entries(t.motion).map(([k, v]) => `    const val motion${k[0].toUpperCase() + k.slice(1)}Ms = ${v}`).join('\n')}
}
`;
}

const targets = [
  [path.join(root, 'web', 'src', 'styles', 'tokens.css'), css],
  [path.join(root, 'android', 'app', 'src', 'main', 'java', 'dev', 'foxfleet', 'app', 'ui', 'Tokens.kt'), kotlin],
];
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check'); let stale = false;
  for (const [file, make] of targets) {
    // Generated content is the same in LF and CRLF checkouts.
    const next = make().replace(/\r\n/g, '\n'), cur = existsSync(file) ? readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : null;
    if (check) { if (cur !== next) { console.error(`stale: ${path.relative(root, file)}`); stale = true; } continue; }
    mkdirSync(path.dirname(file), { recursive: true }); if (cur !== next) writeFileSync(file, next); console.log('wrote', path.relative(root, file));
  }
  if (stale) process.exit(1);
}
